### PR TITLE
Fix cardboard

### LINKED ISSUE #762: Issues with SkinRestorer while using Cardboard for Fabric 1.18
When i upload the plugin, he's detected but he can't load normally. i don't know if it's because of cardboard but with Cardboard we're supposed to be able to use spiggot and bukkit plugins. 
In server log i can read this : 

i joined server's log on this request
[log.txt](https://github.com/SkinsRestorer/SkinsRestorerX/files/7669301/log.txt)

### PR DESCRIPTION
**Pull request by AlexProgrammerDE**
This PR in theory adds support for cardboard, but __in theory__. ACF breaks on it.

Fixes #762

### CODE REVIEW

File: bukkit/src/main/java/net/skinsrestorer/bukkit/skinrefresher/SpigotSkinRefresher.java [hunk 1]
```diff
@@ -63,17 +63,23 @@ public SpigotSkinRefresher(SkinsRestorer plugin, SRLogger log) throws Initialize
...
-                    // Forge
-                    removePlayerEnum = ReflectionUtil.getEnum(playOutPlayerInfo, "Action", "REMOVE_PLAYER");
-                    addPlayerEnum = ReflectionUtil.getEnum(playOutPlayerInfo, "Action", "ADD_PLAYER");
-                } catch (Exception e1) {
-                    Class<?> enumPlayerInfoAction = ReflectionUtil.getNMSClass("EnumPlayerInfoAction", null);
-
-                    // 1.8 or below
-                    removePlayerEnum = ReflectionUtil.getEnum(enumPlayerInfoAction, "REMOVE_PLAYER");
-                    addPlayerEnum = ReflectionUtil.getEnum(enumPlayerInfoAction, "ADD_PLAYER");
+                    Class<?> enumPlayerInfoActionClass = Class.forName("net.minecraft.network.protocol.game.PacketPlayOutPlayerInfo$EnumPlayerInfoAction");
```
Comment (xknat) [inline bukkit/src/main/java/net/skinsrestorer/bukkit/skinrefresher/SpigotSkinRefresher.java:68]: can you add more comments? i am sure what this is for is this only for cardboard?

**Review by xknat — CHANGES_REQUESTED** [review]
LGTM if comments are added

File: bukkit/src/main/java/net/skinsrestorer/bukkit/SkinApplierBukkit.java [hunk 2]
```diff
@@ -215,4 +216,26 @@ private void checkOptFile() {
         log.debug("[Debug] Opt Files: { disableDismountPlayer: " + disableDismountPlayer + ", disableRemountPlayer: " + disableRemountPlayer + ", enableDismountEntities: " + enableDismountEntities + " }");
         optFileChecked = true;
     }
+
+    private boolean isPaper() {
+        if (PaperLib.isPaper() && ReflectionUtil.SERVER_VERSION.isNewer(new ServerVersion(1, 11, 2))) {
+            if (hasPaperMethods()) {
+                return true;
+            } else {
+                log.warning("Paper detected, but the methods are missing. Disabling Paper Refresher.");
```
Comment (xknat) [inline bukkit/src/main/java/net/skinsrestorer/bukkit/SkinApplierBukkit.java]: This should be a debug, as this is not a warning that players should report to us or that will effect the status of the working condition of the plugin (as it will fall back to spigot refresher)

**Review by xknat — CHANGES_REQUESTED** [review]

**Review by xknat — APPROVED** [review]
LGTM
