### PR TITLE
Fix 1.18

### LINKED ISSUE #736: MC 1.18 Support
We are working hard on supporting 1.18 we will give updates on our discord server.

**Known Errors** 
These errors will appear when using mc 1.18 & SkinsRestorer:
```
net.skinsrestorer.api.reflection.exception.ReflectionException: java.lang.NoSuchMethodException: 
net.minecraft.server.level.EntityPlayer.getProfile()
```
```
net.skinsrestorer.api.reflection.exception.ReflectionException: java.lang.NoSuchMethodException: 
net.minecraft.server.level.EntityPlayer.getWorld()
```

### PR DESCRIPTION
**Pull request by AlexProgrammerDE**
Not even close to working anywhere. Just for overview of current changes for team devs.

TODO:
- [ ] add getProperty in applier and have /sr props connect to it (all implementations)

### CODE REVIEW

File: bukkit/src/main/java/net/skinsrestorer/bukkit/SkinApplierBukkit.java [hunk 1]
```diff
@@ -114,18 +121,28 @@ protected void applySkin(Player player, IProperty property) {
...
     public void applyProperty(Player player, IProperty property) {
         try {
-            Object ep = ReflectionUtil.invokeMethod(player.getClass(), player, "getHandle");
-            GameProfile profile = (GameProfile) ReflectionUtil.invokeMethod(ep.getClass(), ep, "getProfile");
+            GameProfile profile = getGameProfile(player);
             profile.getProperties().removeAll("textures");
-            //noinspection unchecked
             profile.getProperties().put("textures", property);
         } catch (ReflectionException e) {
             e.printStackTrace();
```
Comment (xknat) [inline bukkit/src/main/java/net/skinsrestorer/bukkit/SkinApplierBukkit.java:131]: Maybe we should move this to debug and change it to a more humane message informing the user that we don't yet support it. Spitting out errors will only raise more questions and will be used as spam on our discord.

**Review by xknat — CHANGES_REQUESTED** [review]

**Review by xknat — APPROVED** [review]
🙌 🙌 🙌 🙌 🙌
