### PR TITLE
Fix connection to the database using a password with special characters

### LINKED ISSUE #1088: Mysql password containing special characters throws java.sql.SQLInvalidAuthorizationSpecException

### PR DESCRIPTION
**Pull request by anokhovd**
Since some messages in proxy mode are taken from local files (for example, messages for GUI), it is necessary on the backend to load the configuration to set the selected localization as default. Otherwise, there will be a mismatch in the localization of messages between the server part and the proxy server

Also this PR fixes #1088 #1092

### CODE REVIEW

**Comment by xknat** [comment]
Firstly, thank you for creating a pr!
We have recently (Dev builds) added a override called enableSkinStorageAPI.txt wich is described in the backend proxy warning file.
We yet have to advertise this throughout the API and other important places.

Why are we doing this?
Not all config options on the backend are in effect when in proxy mode, so this could confuse new users.
Me and @AlexProgrammerDE are considering splitting the MySQL part of the config.

File: bukkit/src/main/java/net/skinsrestorer/bukkit/SkinsRestorer.java [hunk 1]
```diff
@@ -338,16 +339,6 @@ public void pluginStartup() throws InitializeException {
         }
     }
 
-    private void initConfigAndStorage() throws InitializeException {
-        // Init config files
-        Config.load(dataFolderPath, getResource("config.yml"), srLogger);
-        // Set new default locale because we initialized localeManager early
-        localeManager.setDefaultLocale(LocaleParser.getDefaultLocale());
```
Comment (AlexProgrammerDE) [inline bukkit/src/main/java/net/skinsrestorer/bukkit/SkinsRestorer.java]: These two lines were not added back above.

**Review by AlexProgrammerDE — CHANGES_REQUESTED** [review]

File: bukkit/src/main/java/net/skinsrestorer/bukkit/SkinsRestorer.java (hunk 1 above)
Comment (anokhovd) [reply bukkit/src/main/java/net/skinsrestorer/bukkit/SkinsRestorer.java]: I think the desired locale is already set by default, because we are passing it to `LocaleManager::create` after config is loaded
> `SkinsRestorerAPIShared.getApi().getDefaultForeign().getLocale()`

`DefaultForeignSubject::getLocale` uses the same `LocaleParser::getDefaultLocale`

```java
public class DefaultForeignSubject implements ISRForeign {
    @Override
    public Locale getLocale() {
        return LocaleParser.getDefaultLocale();
    }
}
```

**Review by xknat — CHANGES_REQUESTED** [review]
Keep init storage under enableSkinStorageAPI.txt override?
We should split this setting with a different config just like with MySQL in my opinion

File: bukkit/src/main/java/net/skinsrestorer/bukkit/SkinsRestorer.java (hunk 1 above)
Comment (AlexProgrammerDE) [reply bukkit/src/main/java/net/skinsrestorer/bukkit/SkinsRestorer.java]: Well yes, but it won't work on players with a locale that wasn't translated for SkinsRestorer yet.
image
getDefaultLocale() returns something else after config is loaded, so it should be updated on the locale manager.

Comment (AlexProgrammerDE) [reply bukkit/src/main/java/net/skinsrestorer/bukkit/SkinsRestorer.java]: Actually, this will cause a lot of unintended behavior. May you just drop all your config loading changes and only focus on your key MySQL change?

Comment (AlexProgrammerDE) [reply bukkit/src/main/java/net/skinsrestorer/bukkit/SkinsRestorer.java]: We are planning to split our configs in a future release to fix this config stuff.

**Review by AlexProgrammerDE — APPROVED** [review]
LGTM!

**Review by xknat — APPROVED** [review]
Thanks for the pr!
And sorry for the confusion / internal dialog
Feel free to chat over on our discord if your interested to help us out!
